### ISSUE TITLE
$.data equivalent in DOMtastic?

### ISSUE THREAD

**Issue by matt3224** [webpro/DOMtastic#48] opened 2016-12-11 00:55 UTC
I am playing around with plugins and am wanting to create a few of these. A lot of the examples on how jQuery plugins are structured use $.data to save each instance of the plugin.

One of the best examples is that of [John Dugan](https://john-dugan.com/jquery-plugin-boilerplate-explained/)

If you simply switch jQuery for DOMtastic (using the DOMtastic jquery compat mode too) throws an error. I started to construct my own workaround but thought I would check in with you incase there was a way to do this?

Thanks! 👍

**Comment by webpro** [comment] 2016-12-11 18:58
If the problem is a missing `$.fn.data` function, you could add it yourself. Not sure if that would be enough? There might be more methods missing.

Btw, here's jQuery's implementation: https://github.com/jquery/jquery/blob/master/src/data.js

**Comment by webpro** [comment] 2017-03-12 21:17
Once I'll get BrowserStack running, `data()` will be in the next release (it's in the master branch if you want to try it).

**Comment by webpro** [comment] 2017-03-20 20:56
Released in [v0.13.0](https://github.com/webpro/DOMtastic/releases/tag/0.13.0).

**Closed by webpro** 2017-03-20 20:56 UTC
