### ISSUE TITLE
API documentation website not working correctly

### ISSUE THREAD

**Issue by icflorescu** [webpro/DOMtastic#38] opened 2016-07-28 15:56 UTC
Hi Lars,

The API documentation website stopped working correctly a few days ago. All link hashes invariably lead to the showing just the `BaseClass` page now:

![domtastic-docs-bug](https://cloud.githubusercontent.com/assets/581999/17219559/74ca2eb6-54f4-11e6-9853-baa7f409be24.jpg)

Let me know if there's anything I can assist with to fix this.

P.S. Thanks for creating DOMtastic! ;-)

**Comment by webpro** [comment] 2016-07-28 16:00
Yeah I know. I think the problem is that I've refactored quite some exports a while ago and [dox](https://github.com/tj/dox) doesn't support this well. If I recall correctly, the issue was something like not resolving eg. the "siblings" function name from `export const siblings = function(selector) {}`.

**Comment by olsonpm** [comment] 2016-08-05 06:01
I guess this should be obvious - but an easy workaround for now is just to clone it locally, checkout the second-to-latest commit on `gh-pages` and open the doc/index.html file.

**Comment by webpro** [comment] 2016-08-05 06:16
I'm going to take a stab at fixing this today.

**Comment by webpro** [comment] 2016-08-05 09:48
Looks like https://domtastic.js.org/doc/ is OK again. Please let me know about anything incorrect.

**Closed by webpro** 2016-08-05 09:48 UTC

**Comment by icflorescu** [comment] 2016-08-05 15:09
Thanks a lot!
